#!/bin/bash
# Gentoo Startup script for qmail's SMTP daemon (logging)
# $Header$

SERVICE=smtp
. /var/qmail/bin/qmail-config-system && \
eval exec /usr/bin/setuidgid qmaill /usr/bin/multilog ${LOG_OPTS} ${LOG_DEST}
