#!/sbin/runscript
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header$

depend() {
	need net
}

start() {
	ebegin "Starting iperf server"
	start-stop-daemon --start --quiet \
		--exec /usr/bin/iperf -- -s -D ${IPERF_OPTS} &>/dev/null
	eend $?
}

stop() {
	ebegin "Shutting down iperf server"
	start-stop-daemon --stop --quiet --exec /usr/bin/iperf
	eend $?
}
