#!/sbin/runscript
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header$

depend() {
	need net
	use dns
}

start() {
	ebegin "Starting silcd"
	start-stop-daemon --start --quiet --exec /usr/sbin/silcd -- -f /etc/silc/silcd.conf >/dev/null 2>&1
	eend $?
}

stop() {
	ebegin "Shutting down silcd"
	start-stop-daemon --stop --pidfile /var/run/silcd.pid
	eend $?
}
