#!/sbin/runscript
# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header$

depend() {
	need net
	use logger
}

start() {
	ebegin "Starting Corosync Cluster Engine"
	start-stop-daemon --start -q --exec /usr/sbin/corosync \
		--pidfile /var/run/corosync.pid --make-pidfile --background \
		-- -f
	eend $?
}

stop() {
	ebegin "Stopping Corosync Cluster Engine"
	start-stop-daemon --stop -q --pidfile /var/run/corosync.pid
	eend $?
}
