#!/sbin/runscript
# Copyright 1999-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header$

depend() {
	before sshd
}

start() {
	ebegin "Starting FreeNX server"
	/usr/bin/nxserver --cleanup >/dev/null 2>&1
	/usr/bin/nxserver --start >/dev/null 2>&1
	eend $?
}

stop() {
	ebegin "Stopping FreeNX server"
	/usr/bin/nxserver --stop >/dev/null 2>&1
	/usr/bin/nxserver --cleanup >/dev/null 2>&1
	eend 0
}

# vim:ts=4
